### PR TITLE
Stage -> Prod Sync (April 2024 Release)

### PR DESCRIPTION
**Pull request by anthonypetersen**
Issues Addressed
-----
* [Sync SendGrid Data to BQ](https://github.com/episphere/connect/issues/835) - @jhflorey 
* [One Notifications Run Per Day](https://github.com/episphere/connect/issues/930) - @we-ai 
* [Add Stub Variables](https://github.com/episphere/connect/issues/962) - @jhflorey 
* [Dry Run Functionality](https://github.com/episphere/connect/discussions/934) - @we-ai 
* [Updated Home Collection Sorting](https://github.com/episphere/connect/issues/960) - @JoeArmani 
* [Remove getParticipants Filter Options](https://github.com/episphere/connectFaas/pull/573) - @JoeArmani 
* [Set Refusal / Withdraw on Data Destruction](https://github.com/episphere/connect/issues/959) - @jhflorey 
* [Simplify SQL Query](https://github.com/episphere/connectFaas/pull/575) - @we-ai 
* [Block API Data on Withdraw](https://github.com/episphere/connect/issues/935) - @bransteitterbr 
* [Added Home Collection API Endpoint](https://github.com/episphere/connect/issues/955) - @Gbarra9 
* [Handle Mixed Data Types](https://github.com/episphere/connect/issues/976) - @we-ai

### CODE REVIEW

**Review by Gbarra9 — APPROVED** [review]
My changes were tested in stage and ready for prod

**Review by we-ai — APPROVED** [review]
My updates were tested in stage, and are ready for prod.

**Review by jhflorey — APPROVED** [review]

**Comment by jhflorey** [comment]
My changes were tested in stage and ready for prod

**Review by JoeArmani — APPROVED** [review]
My changes are tested in stage and ready for prod.

**Pull request merged**
