### PR TITLE
Stage -> Prod Sync (December 2024)

### PR DESCRIPTION
**Pull request by we-ai**
Issues Addressed:

- [Create Passthrough API for BQ data](https://github.com/episphere/connect/issues/1126) (@bransteitterbr)
- [Prevent two baseline kits assigned to same participant](https://github.com/episphere/connect/issues/1109) (@amber-emmes)
- [Initial home mouthwash work, re-implemented and tested](https://github.com/episphere/connectFaas/pull/688) (@amber-emmes)
- [Update Response handling from Submit Endpoint](https://github.com/episphere/connect/issues/1168) (@JoeArmani)
- [NORC Survey Reset Tool](https://github.com/episphere/connect/issues/1130) (@Gbarra9)
- [NORC enable incentive eligible](https://github.com/episphere/connect/issues/1131) (@Gbarra9)
- [User Profile Enhancements for Contact Information](https://github.com/episphere/connect/issues/1149) (@jhflory)
- Package updates: [Bump json-schema and jsprim](https://github.com/episphere/connectFaas/pull/338), [Bump axios from 0.21.1 to 0.21.4](https://github.com/episphere/connectFaas/pull/337), [Bump ansi-regex from 4.1.0 to 4.1.1](https://github.com/episphere/connectFaas/pull/336), [Bump jsonwebtoken, firebase-admin and twilio](https://github.com/episphere/connectFaas/pull/339), [Bump node-forge, google-p12-pem and firebase-admin](https://github.com/episphere/connectFaas/pull/340), [update firebase-admin package](https://github.com/episphere/connectFaas/pull/696) (@anthonypetersen, @joeArmani)
- [Cancer Screening History Survey](https://github.com/episphere/connect/issues/1145) (@we-ai)
- [Update submitSpecimen derivations and routine](https://github.com/episphere/connectFaas/pull/701) (@JoeArmani)

### CODE REVIEW

**Review by anthonypetersen — APPROVED** [review]
approved and ready for prod

**Review by bransteitterbr — APPROVED** [review]

**Review by jhflorey — APPROVED** [review]

**Comment by jhflorey** [comment]
Ready for prod

**Review by Gbarra9 — APPROVED** [review]
Changes tested in stage, ready for prod

**Comment by we-ai** [comment]
Ready for prod.

**Review by JoeArmani — APPROVED** [review]
tested in stage, ready for prod

**Review by amber-emmes — APPROVED** [review]
All of my changes have been approved in stage and are ready for prod.

**Review by JoeArmani — APPROVED** [review]
My additional changes are tested and ready for prod

**Pull request merged**
