### PR TITLE
Dev -> Stage sync (Aug. release)

### PR DESCRIPTION
**Pull request by we-ai**
Issues Addressed:
- https://github.com/episphere/connect/issues/676 (@abhinavjonnada82)
- https://github.com/episphere/connect/issues/691 (@anthonypetersen)
- https://github.com/episphere/connect/issues/669 (@jhflorey)
- https://github.com/episphere/connect/issues/658. Further updates (@jhflorey)
- https://github.com/episphere/connect/issues/685 (@Gbarra9, @JoeArmani)
- https://github.com/episphere/connect/issues/654. Further updates (@JoeArmani)
- https://github.com/episphere/connect/issues/631. Added API endpoints (@abhinavjonnada82)
- https://github.com/episphere/connect/issues/689 (@abhinavjonnada82)
- https://github.com/episphere/connect/issues/692 (@we-ai)
- https://github.com/episphere/connectFaas/pull/413 (@JoeArmani)
- https://github.com/episphere/connect/issues/695 (@we-ai)

### CODE REVIEW

**Review by anthonypetersen — APPROVED** [review]

**Comment by we-ai** [comment]
My updates (notifications sending and notifications backup to BQ) were tested in dev, and are ready for stage sync.

**Comment by JoeArmani** [comment]
My ConnectFaas updates were tested in dev and are ready for stage sync.

**Comment by abhinavjonnada82** [comment]
Tested in dev & ready for stage.

**Comment by anthonypetersen** [comment]
tested and ready for stage

**Comment by jhflorey** [comment]
tested and ready for stage

**Pull request merged**
