### PR TITLE
Stage -> Prod Sync (September 2024)

### PR DESCRIPTION
**Pull request by we-ai**
Issues Addressed:
- [NORC SSO Updates](https://github.com/episphere/connectFaas/pull/639) (@anthonypetersen)
- [Fix bug in dry run of notifications](https://github.com/episphere/connect/issues/1107) (@we-ai)
- [Automate verification of participants](https://github.com/episphere/connect/issues/1084) (@amber-emmes)
- [Supply Kit and Return Kit- Consistency check and force uppercase- Biospecimen](https://github.com/episphere/connect/issues/1089) (@amber-emmes)
- [Ingesting Opt-Out/In Keywords Data from Twilio](https://github.com/episphere/connect/issues/1104) (@we-ai)
- [Upgrade handling of notification specification conditions](https://github.com/episphere/connect/issues/1064) (@we-ai)
- [Implementing an End Date/Stop Function for Notification Specs in SMDB](https://github.com/episphere/connect/issues/1112) (@we-ai)
- [Update regex for Home mouthwash collection query](https://github.com/episphere/connect/issues/1118) (@Gbarra9 )
- [Add variables to be retained in the stub record](https://github.com/episphere/connect/issues/1122) (@jhflorey)
- [2024 Connect Experience Survey requirements](https://github.com/episphere/connect/issues/1073) (@bransteitterbr, @amber-emmes)

### CODE REVIEW

**Review by Gbarra9 — APPROVED** [review]
My change was tested in stage and ready for prod.

**Review by anthonypetersen — APPROVED** [review]
ready for prod

**Comment by jhflorey** [comment]
my changes were tested in stage and ready for prod

**Review by jhflorey — APPROVED** [review]

**Comment by we-ai** [comment]
My updates are ready for prod.

**Review by amber-emmes — APPROVED** [review]
All my and Brian's changes are ready for prod.

**Pull request merged**
