### PR TITLE
Stage -> Prod Sync (August 2024)

### PR DESCRIPTION
**Pull request by anthonypetersen**
Issues Addressed:

- https://github.com/episphere/connect/issues/866 (@JoeArmani)
- https://github.com/episphere/connectFaas/pull/632 (@anthonypetersen)
- https://github.com/episphere/connect/issues/1063 (@Gbarra9)
- https://github.com/episphere/connect/issues/1006 (@jhflorey)
- https://github.com/episphere/connect/issues/1052 (@we-ai)
- https://github.com/episphere/connectFaas/pull/636 (@we-ai)

### CODE REVIEW

**Review by jhflorey — APPROVED** [review]

**Review by Gbarra9 — APPROVED** [review]
My change was tested in stage and is ready for prod.

**Comment by jhflorey** [comment]
My changes were tested in stage and ready for prod.

**Comment by we-ai** [comment]
My updates have been tested in stage, and are ready for production.

**Review by we-ai — APPROVED** [review]

**Comment by anthonypetersen** [comment]
changes are ready for prod

**Review by JoeArmani — APPROVED** [review]
My changes are tested in stage, ready for prod.

**Pull request merged**
