### PR TITLE
Stage -> Prod Sync (October Release)

### PR DESCRIPTION
**Pull request by anthonypetersen**
Issues Addressed:
* https://github.com/episphere/connect/issues/619 (@JoeArmani)
* https://github.com/episphere/connect/issues/740 (@Gbarra9)
* https://github.com/episphere/connect/issues/646 (@bransteitterbr)
* https://github.com/episphere/connect/issues/737 (@anthonypetersen)
* https://github.com/episphere/connect/issues/800 (@JoeArmani)
* https://github.com/episphere/connect/issues/805 (@JoeArmani)

### CODE REVIEW

**Comment by anthonypetersen** [comment]
my changes have been approved and are ready for prod

**Review by Davinkjohnson — APPROVED** [review]
I'll approve Brian's changes on his behalf as he's out on leave. Tony, if you add me as a reviewer, I'll approve his changes. (they've been tested and approved in stage)

**Review by we-ai — APPROVED** [review]

**Review by JoeArmani — APPROVED** [review]
All of my changes are tested/approved in stage and ready for prod.

**Review by Gbarra9 — APPROVED** [review]
My changes are ready to be moved forward.
Note: The other parts to it will be updated at a later time.

**Pull request merged**
