### PR TITLE
Dev -> Stage Sync (Jan. Release)

### PR DESCRIPTION
**Pull request by we-ai**
Issues Addressed:
- https://github.com/episphere/connect/issues/833 (@JoeArmani)
- https://github.com/episphere/connect/issues/675 (@JoeArmani)
- https://github.com/episphere/connect/issues/856 (@JoeArmani)
- https://github.com/episphere/connect/issues/817 (@JoeArmani)
- https://github.com/episphere/connect/issues/857 (@abhinavjonnada82)
- https://github.com/episphere/connect/issues/718 (@bransteitterbr)
- https://github.com/episphere/connect/issues/640#issuecomment-1896266558, PR#507 (@jhflorey).
- https://github.com/episphere/connect/issues/810 (@abhinavjonnada82)
- https://github.com/episphere/connect/issues/712 (@anthonypetersen)
- https://github.com/episphere/connect/issues/827 (@we-ai)
- https://github.com/episphere/connect/issues/860 (@we-ai)

### CODE REVIEW

**Comment by jhflorey** [comment]
My change is ready to stage

**Review by jhflorey — APPROVED** [review]

**Review by anthonypetersen — APPROVED** [review]

**Comment by JoeArmani** [comment]
I have one item still pending testing. I'll update once testing is complete.

Tested and ready for stage:
https://github.com/episphere/connect/issues/833 (@JoeArmani)
https://github.com/episphere/connect/issues/856 (@JoeArmani)
https://github.com/episphere/connect/issues/817 (@JoeArmani)

Awaiting testing:
https://github.com/episphere/connect/issues/675 (@JoeArmani)

**Comment by bransteitterbr** [comment]
Ready for stage

**Comment by we-ai** [comment]
Tested in dev and ready for stage.

**Pull request merged**
