### PR TITLE
Dev -> Stage Sync (Mar. Release)

### PR DESCRIPTION
**Pull request by we-ai**
Issues Addressed:
- https://github.com/episphere/connect/issues/636#issuecomment-1984579188. Add conditions to delete participant (@jhflorey )
- https://github.com/episphere/connect/issues/901 (@Gbarra9)
- https://github.com/episphere/connect/issues/911 (@Gbarra9)
- https://github.com/episphere/connect/issues/640#issuecomment-1994462383. Update data for new SOP requirement (@jhflorey)
- ~https://github.com/episphere/connect/issues/870 (@anthonypetersen)~
- https://github.com/episphere/connect/issues/828 (@jhflorey)

### CODE REVIEW

**Comment by anthonypetersen** [comment]
will likely be pulling my code out for this release due to external prod API server not being ready - will update by end of the week

**Comment by anthonypetersen** [comment]
While most of my code is staying in the release, the code responsible for triggering everything has been commented out so the functionality will not be moving forward this release.

**Comment by Gbarra9** [comment]
Issue#911 - tested in dev and ready for stage by Kathleen
Issue#901 - My update does not seem to be dependent on the additional email notification testing. I am going to wait till Monday to have the final decision whether the email notification testing is a prerequisite to having my changes being approved and tested.

**Comment by jhflorey** [comment]
https://github.com/episphere/connect/issues/636#issuecomment-2018100902 Ready for Stage

**Review by Gbarra9 — APPROVED** [review]

**Comment by jhflorey** [comment]
https://github.com/episphere/connect/issues/640 Ready for Stage

**Comment by jhflorey** [comment]
https://github.com/episphere/connect/issues/828 Ready for Stage

**Pull request merged**
