### PR TITLE
backup notifications to BQ

### PR DESCRIPTION
**Pull request by we-ai**
This PR backs up "notifications" collection in Firestore to BigQuery, as described in [#695](https://github.com/episphere/connect/issues/695).
Currently the backup occurs once per day.

### CODE REVIEW

**Comment by we-ai** [comment]
> 

I use the data cleanup scheduler which runs once per day.

**Review by JoeArmani — APPROVED** [review]
looks good

Question out of curiosity: do we just use the storage bucket for long-term storage as backup data, or are there other uses?

**Comment by we-ai** [comment]
> 

The backups are kept for 1 month, for data recoveries in case any un-intended data changes happen. I may be wrong on this.

**Comment by anthonypetersen** [comment]
> The backups are kept for 1 month, for data recoveries in case any un-intended data changes happen. I may be wrong on this.

Our current rules on the bucket keep backups for 180 days

**Pull request merged**
