### PR TITLE
Stage -> Prod Sync (Aug. Release) 

### PR DESCRIPTION
**Pull request by we-ai**
Issues Addressed:
- https://github.com/episphere/connect/issues/676 (@abhinavjonnada82)
- https://github.com/episphere/connect/issues/691 (@anthonypetersen)
- https://github.com/episphere/connect/issues/669 (@jhflorey)
- https://github.com/episphere/connect/issues/658. Further updates (@jhflorey)
- https://github.com/episphere/connect/issues/685 (@Gbarra9, @JoeArmani)
- https://github.com/episphere/connect/issues/654. Further updates (@JoeArmani)
- https://github.com/episphere/connect/issues/631. Added API endpoints (@abhinavjonnada82)
- https://github.com/episphere/connect/issues/689 (@abhinavjonnada82)
- https://github.com/episphere/connect/issues/692 (@we-ai)
- https://github.com/episphere/connectFaas/pull/413 (@JoeArmani)
- https://github.com/episphere/connect/issues/695 (@we-ai)

### CODE REVIEW

**Comment by anthonypetersen** [comment]
changes tested and ready for prod

**Review by anthonypetersen — APPROVED** [review]

**Comment by abhinavjonnada82** [comment]
Looks good

**Comment by jhflorey** [comment]
Tested and ready for prod
 - https://github.com/episphere/connect/issues/658#issuecomment-1703084116
 - https://github.com/episphere/connect/issues/658#issuecomment-1706621859

**Comment by abhinavjonnada82** [comment]
Looks good & can move forward.

**Comment by JoeArmani** [comment]
Tested and ready for prod.

**Comment by we-ai** [comment]
Notification emails sending and Notifications backups to BQ were tested in stage, and are ready for production.

**Pull request merged**
