### PR TITLE
Dev -> Stage (November Release)

### PR DESCRIPTION
**Pull request by we-ai**
Issues Addressed:
- https://github.com/episphere/connect/issues/771. Add home collection APIs (@abhinavjonnada82)
- ~https://github.com/episphere/connectFaas/pull/449 (@Gbarra9)~
- https://github.com/episphere/connect/issues/766 (@jhflorey)
- https://github.com/episphere/connect/issues/813 (@abhinavjonnada82)
- https://github.com/episphere/connect/issues/736 (@anthonypetersen)
- https://github.com/episphere/connect/issues/802 (@abhinavjonnada82)
- https://github.com/episphere/connect/issues/803 (@abhinavjonnada82)
- https://github.com/episphere/connect/issues/804 (@abhinavjonnada82)
- https://github.com/episphere/connect/issues/818 (@we-ai)
- https://github.com/episphere/connectFaas/pull/462 (@JoeArmani)
- https://github.com/episphere/connect/issues/675 (@JoeArmani)

### CODE REVIEW

**Review by anthonypetersen — APPROVED** [review]
tested & ready for stage

**Comment by Gbarra9** [comment]
My change were already tested and is in Prod, prior to the "Dev -> Stage (November Release)." The change was added to stage (https://github.com/episphere/connectFaas/pull/454) via cherry pick and then moved to prod (https://github.com/episphere/connectFaas/pull/455) via stage to prod sync

Issues are Closed:
- https://github.com/episphere/connect/issues/806
- https://github.com/episphere/connect/issues/740

**Review by Gbarra9 — APPROVED** [review]

**Comment by jhflorey** [comment]
My change was tested in dev and is ready for stage.

https://github.com/episphere/connect/issues/766

**Comment by we-ai** [comment]
My update ( sync `kitAssembly` to BQ) was tested in dev and is ready for stage.

**Comment by JoeArmani** [comment]
Streck tube data check: tested in dev, ready for stage.
RCA variables: awaiting data push from HP for testing & verification.

**Review by JoeArmani — APPROVED** [review]

**Pull request merged**
