### PR TITLE
Dev -> Stage Sync (Sep. Release)

### PR DESCRIPTION
**Pull request by we-ai**
Issues Addressed:
- https://github.com/episphere/connect/issues/631. Update Daily Reports Page API (@abhinavjonnada82).
- https://github.com/episphere/connect/issues/625. Update ship API (@JoeArmani).
- https://github.com/episphere/dashboard/issues/23. Update data retrieval for SMDB dashboard metrics (@we-ai).
- https://github.com/episphere/biospecimen/issues/548. Improve bptl's packages in transit manifest loading (@Gbarra9).
- https://github.com/episphere/connect/issues/703. SSN updates so that it acts like other surveys (@bransteitterbr)
- https://github.com/episphere/biospecimen/issues/564 (@abhinavjonnada82)

### CODE REVIEW

**Review by anthonypetersen — APPROVED** [review]

**Comment by we-ai** [comment]
My updates are ready for stage.

**Comment by JoeArmani** [comment]
My updates have been tested in dev and they're ready for stage.

**Comment by Gbarra9** [comment]
My update was tested in dev and ready for stage

**Comment by bransteitterbr** [comment]
My update was tested in dev and is ready for stage

**Comment by abhinavjonnada82** [comment]
My updates are ready for Stage as well!

**Comment by abhinavjonnada82** [comment]
Looks good & can move forward!

**Pull request merged**
