### PR TITLE
Stage -> Prod (November Release)

### PR DESCRIPTION
**Pull request by we-ai**
Issues Addressed:
- https://github.com/episphere/connect/issues/771. Add home collection APIs (@abhinavjonnada82)
- https://github.com/episphere/connect/issues/766 (@jhflorey)
- https://github.com/episphere/connect/issues/813 (@abhinavjonnada82)
- ~https://github.com/episphere/connect/issues/736 (@anthonypetersen)~
- https://github.com/episphere/connect/issues/802 (@abhinavjonnada82)
- https://github.com/episphere/connect/issues/803 (@abhinavjonnada82)
- https://github.com/episphere/connect/issues/804 (@abhinavjonnada82)
- https://github.com/episphere/connect/issues/818 (@we-ai)
- https://github.com/episphere/connectFaas/pull/462 (@JoeArmani)
- ~https://github.com/episphere/connect/issues/675 (@JoeArmani)~
- https://github.com/episphere/connect/issues/825 (@we-ai)
- https://github.com/episphere/connect/issues/835 (@we-ai)

### CODE REVIEW

**Comment by jhflorey** [comment]
My PR looks good and ready for prod - Already had sendgrid data in firestore.

**Comment by we-ai** [comment]
My updates (sync `kitAssembly` and `mouthwash_v1` to BQ) were confirmed in stage, and are ready for production.

**Comment by anthonypetersen** [comment]
Removing myself and @JoeArmani as reviewers of this PR - our changes have both been pulled from this release cycle.

**Review by JoeArmani — APPROVED** [review]
My changes have been tested in stage and they're ready for prod.

**Comment by we-ai** [comment]
The 3 collections (`kitAssembly`, `mouthwash_v1`, `sendgridTracking`) were  confirmed synced to BQ in stage. The update are ready for prod.

**Pull request merged**
