### PR TITLE
Stage -> Prod Sync (July 2024 Release)

### PR DESCRIPTION
**Pull request by we-ai**
Issues Addressed:
- https://github.com/episphere/connect/issues/1034 (@jhflorey)
- https://github.com/episphere/connect/issues/1048 (@JoeArmani)
- https://github.com/episphere/connectFaas/pull/613 (@anthonypetersen)
- https://github.com/episphere/connect/issues/1016 (@we-ai)
- https://github.com/episphere/connect/issues/1056 (@jhflorey)
- https://github.com/episphere/connect/issues/1057 (@jhflorey)
- https://github.com/episphere/connect/issues/1038 (@amber-emmes)
- https://github.com/episphere/connectFaas/pull/622 (@anthonypetersen)
- https://github.com/episphere/connect/issues/1066 (@JoeArmani)

### CODE REVIEW

**Review by anthonypetersen — APPROVED** [review]
changes are ready for prod

**Review by amber-emmes — APPROVED** [review]
My work is ready for prod.

**Comment by we-ai** [comment]
My updates are ready for prod.

**Review by JoeArmani — APPROVED** [review]
my changes are ready for prod

**Review by jhflorey — APPROVED** [review]

**Comment by jhflorey** [comment]
My changes are ready to prod

**Pull request merged**
