### PR TITLE
Dev -> Stage Sync (August 2024)

### PR DESCRIPTION
**Pull request by anthonypetersen**
Issues Addressed:

- https://github.com/episphere/connect/issues/866 (@JoeArmani)
- https://github.com/episphere/connectFaas/pull/632 (@anthonypetersen)
- https://github.com/episphere/connect/issues/1063 (@Gbarra9)
- https://github.com/episphere/connect/issues/1006 (@jhflorey)
- https://github.com/episphere/connect/issues/1052 (@we-ai)
- https://github.com/episphere/connectFaas/pull/636 (@we-ai)

### CODE REVIEW

**Comment by we-ai** [comment]
My updates were tested in dev and are ready for stage merge.

**Review by Gbarra9 — APPROVED** [review]
My change was tested in dev and ready for stage.

**Review by we-ai — APPROVED** [review]

**Comment by jhflorey** [comment]
My change was tested in dev and ready for stage.

**Review by JoeArmani — APPROVED** [review]
My changes have been tested in dev. Ready for stage.

**Comment by anthonypetersen** [comment]
changes are ready for stage

**Pull request merged**
