### PR TITLE
[#669] Add new campaign type for Research Registry

### PR DESCRIPTION
**Pull request by jhflorey**
This PR addresses issue https://github.com/episphere/connect/issues/669

image

### CODE REVIEW

**Review by JoeArmani — APPROVED** [review]
Add campaign type Research Registry (208952854). looks good

**Review by anthonypetersen — APPROVED** [review]
very nice

**Comment by Davinkjohnson** [comment]
Late add request: Also include another new Concept ID for pop-ups: 296312382

@jhflorey Can you please get this CID added to the file today?

**Comment by jhflorey** [comment]
@Davinkjohnson https://github.com/episphere/connectFaas/pull/402

**Pull request merged**
