### PR TITLE
Dev -> Stage Sync (May 2024 Release)

### PR DESCRIPTION
**Pull request by we-ai**
Issues Addressed:
- [Allow longer timeout in prod for functions handling large number of notifications](https://github.com/episphere/connectFaas/pull/590) (@we-ai)
- [Sync changes in stage](https://github.com/episphere/connectFaas/pull/591) (@anthonypetersen)
- https://github.com/episphere/connect/issues/1009 (@JoeArmani)
- https://github.com/episphere/connectFaas/pull/594 (@amber-emmes)
- ~https://github.com/episphere/connectFaas/pull/595 (@JoeArmani). Related to [issue #866](https://github.com/episphere/connect/issues/866).~

### CODE REVIEW

**Comment by amber-emmes** [comment]
My work is still awaiting testing in dev and is not yet ready to merge.

**Review by anthonypetersen — APPROVED** [review]
ready for stage

**Comment by we-ai** [comment]
Ready for stage.

**Comment by JoeArmani** [comment]
My RCA Variables changes are not being tested this cycle, so this part should not advance to stage. @anthonypetersen, do you need me to do anything on this front?

**Comment by we-ai** [comment]
> My RCA Variables changes are not being tested this cycle, so this part should not advance to stage. @anthonypetersen, do you need me to do anything on this front?

Will merging those RCA variable changes to stage break things in stage? If not, maybe the easier solution is to merge them to stage, but exclude them when merging to prod. Or should those changes be reverted? @anthonypetersen @JoeArmani

**Comment by JoeArmani** [comment]
> > My RCA Variables changes are not being tested this cycle, so this part should not advance to stage. @anthonypetersen, do you need me to do anything on this front?
> 
> Will merging those RCA variable changes to stage break things in stage? If not, maybe the easier solution is to merge them to stage, but exclude them when merging to prod. Or should those changes be reverted? @anthonypetersen @JoeArmani

The changes will not break stage, they are more accurate to current specs than the current version in stage...BUT...they have not been tested. I have no preference on merging or reverting. Thanks!

Also, my getParticipant API memory changes have been verified in GCP and they're ready for stage.

**Comment by amber-emmes** [comment]
My work (#594) is ready for stage.

**Review by amber-emmes — APPROVED** [review]

**Comment by we-ai** [comment]
> The changes will not break stage, they are more accurate to current specs than the current version in stage...BUT...they have not been tested. I have no preference on merging or reverting. Thanks!
> 

Another option is commenting those changes out before stage merge.

**Comment by anthonypetersen** [comment]
> > > My RCA Variables changes are not being tested this cycle, so this part should not advance to stage. @anthonypetersen, do you need me to do anything on this front?
> > 
> > 
> > Will merging those RCA variable changes to stage break things in stage? If not, maybe the easier solution is to merge them to stage, but exclude them when merging to prod. Or should those changes be reverted? @anthonypetersen @JoeArmani
> 
> The changes will not break stage, they are more accurate to current specs than the current version in stage...BUT...they have not been tested. I have no preference on merging or reverting. Thanks!
> 
> Also, my getParticipant API memory changes have been verified in GCP and they're ready for stage.

I would suggest reverting until they are ready to test.

**Review by JoeArmani — COMMENTED** [review]
getParticipants API changes verified. RCA Variables changes (not yet tested) reverted. Ready for stage.

**Pull request merged**
