### PR TITLE
Dev -> Stage Sync (April 2024 Release)

### PR DESCRIPTION
**Pull request by anthonypetersen**
Issues Addressed
-----
* [Sync SendGrid Data to BQ](https://github.com/episphere/connect/issues/835) - @jhflorey 
* [One Notifications Run Per Day](https://github.com/episphere/connect/issues/930) - @we-ai 
* [Add Stub Variables](https://github.com/episphere/connect/issues/962) - @jhflorey 
* [Dry Run Functionality](https://github.com/episphere/connect/discussions/934) - @we-ai 
* [Updated Home Collection Sorting](https://github.com/episphere/connect/issues/960) - @JoeArmani 
* [Remove getParticipants Filter Options](https://github.com/episphere/connectFaas/pull/573) - @JoeArmani 
* [Set Refusal / Withdraw on Data Destruction](https://github.com/episphere/connect/issues/959) - @jhflorey 
* [Simplify SQL Query](https://github.com/episphere/connectFaas/pull/575) - @we-ai 
* [Block API Data on Withdraw](https://github.com/episphere/connect/issues/935) - @bransteitterbr 
* [Added Home Collection API Endpoint](https://github.com/episphere/connect/issues/955) - @Gbarra9 
* [Handle Mixed Data Types](https://github.com/episphere/connect/issues/976) - @we-ai 
* [Anniversary Newsletter Formatting Issues](https://github.com/episphere/connect/issues/944) - @jhflorey

### CODE REVIEW

**Comment by we-ai** [comment]
My updates were tested in dev, and are ready for stage.

**Review by we-ai — APPROVED** [review]

**Review by JoeArmani — APPROVED** [review]
My changes are tested in dev and ready for stage.

**Review by Gbarra9 — APPROVED** [review]
My changes are tested in dev and ready for stage.

@anthonypetersen When dev / stage sync is completed. I have a composite index that needs to be created. Thank you.

Collection ID: participants

Fields Indexed: 
`173836415`.`266600170`.`319972665`.`221592017` Ascending `173836415`.`266600170`.`319972665`.`661940160` Ascending __name__ Ascending

Screenshot 2024-04-19 at 5 00 22 PM

**Comment by bransteitterbr** [comment]
Tested in stage ready for dev

**Review by jhflorey — APPROVED** [review]

**Comment by jhflorey** [comment]
My changes were tested in dev and ready for stage.

**Pull request merged**
