### PR TITLE
Dev -> Stage Sync (September 2024)

### PR DESCRIPTION
**Pull request by we-ai**
Issues Addressed:
- [NORC SSO Updates](https://github.com/episphere/connectFaas/pull/639) (@anthonypetersen)
- [Fix bug in dry run of notifications](https://github.com/episphere/connect/issues/1107) (@we-ai)
- [Automate verification of participants](https://github.com/episphere/connect/issues/1084) (@amber-emmes)
- [Supply Kit and Return Kit- Consistency check and force uppercase- Biospecimen](https://github.com/episphere/connect/issues/1089) (@amber-emmes)
- [Ingesting Opt-Out/In Keywords Data from Twilio](https://github.com/episphere/connect/issues/1104) (@we-ai)
- [Upgrade handling of notification specification conditions](https://github.com/episphere/connect/issues/1064) (@we-ai)
- [Implementing an End Date/Stop Function for Notification Specs in SMDB](https://github.com/episphere/connect/issues/1112) (@we-ai)
- [Update regex for Home mouthwash collection query](https://github.com/episphere/connect/issues/1118) (@Gbarra9 )
- [Add variables to be retained in the stub record](https://github.com/episphere/connect/issues/1122) (@jhflorey)
- [2024 Connect Experience Survey requirements](https://github.com/episphere/connect/issues/1073) (@bransteitterbr, @amber-emmes)

### CODE REVIEW

**Review by anthonypetersen — APPROVED** [review]
changes are ready for stage

**Comment by we-ai** [comment]
My updates are ready for stage.

**Review by Gbarra9 — APPROVED** [review]
My change was tested in dev and ready to be moved to stage.

**Comment by amber-emmes** [comment]
Confirming for Brian, who is out, that [1073](https://github.com/episphere/connect/issues/1073) is ready for stage. All of both my and Brian's changes are ready to go out.

**Comment by jhflorey** [comment]
my changes will be tested in stage. https://github.com/episphere/connect/issues/1122#issuecomment-2383255478

**Review by jhflorey — APPROVED** [review]

**Pull request merged**
